name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: |
        cd nerdMath
        npm ci
        
    - name: Build Docker image
      run: |
        cd nerdMath
        docker build -t nerdmath .
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/nerdMath
          git pull origin main
          docker-compose down
          # 환경변수와 함께 컨테이너 재시작
          docker-compose up -d --build
