version: '3.8'

services:
  nerdmath-api:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
