version: '3.8'

services:
  nerdmath-api:
    build: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
