name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'nerdMath/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd nerdMath
        npm ci --prefer-offline --no-audit
        # Retry if failed due to rate limit
        if [ $? -ne 0 ]; then
          echo "Retrying npm install after rate limit error..."
          sleep 30
          npm ci --prefer-offline --no-audit
        fi
        
    - name: Build Docker image
      run: |
        cd nerdMath
        docker build -t nerdmath .
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p /home/ubuntu/nerdMath
          cd /home/ubuntu/nerdMath
          if [ ! -d ".git" ]; then
            git clone https://github.com/Seeds-PROJECT-TEAM/BE.git .
          else
            git pull origin main
          fi
          cd nerdMath
          # Install Docker Compose using snap (simplest method)
          if ! command -v docker-compose &> /dev/null; then
            sudo snap install docker-compose
          fi
          docker-compose down || true
          docker-compose up -d --build
